the :- N/N : (lambda $0:<e,t> $0)
the :- NP/NP : (lambda $0:e $0)
the :- NP/N : (lambda $0:<e,t> (the:<<e,t>,e> $0))
//pickup :- S/NP : (lambda $0:obj (pickup:<obj,t> $0))
pickup :- S/NP : (lambda $0:obj (pickup:<obj,t> $0))